input {
  beats {
    port => 5044
  }
}

filter {
  if [container][name] == "nginx" {
    grok {
      match => {
        "message" => "%{IPORHOST:client.ip} - %{DATA:user.name} \[%{HTTPDATE:nginx.access.time}\] \"%{WORD:http.request.method} %{DATA:url.original} HTTP/%{NUMBER:http.version}\" %{NUMBER:http.response.status_code:int} %{NUMBER:http.response.body.bytes:int} \"%{DATA:http.request.referrer}\" \"%{DATA:user_agent.original}\""
      }
    }
  } else if [container][name] == "mysql" {
    grok {
      match => {
        "message" => ["%{TIMESTAMP_ISO8601:mysql.time} %{NUMBER:mysql.thread_id} \[%{LOGLEVEL:log.level}\] \[%{DATA:mysql.subsystem}\] %{GREEDYDATA:mysql.message}", "%{GREEDYDATA:mysql.message}"]
      }
    }
  } else if [container][name] == "php-fpm" {
    grok {
      match => {
        "message" => ["\[%{DATA:php_fpm.time}\] %{LOGLEVEL:log.level}: %{GREEDYDATA:php_fpm.message}", "%{GREEDYDATA:php_fpm.message}"]
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-cms-%{+YYYY.MM.dd}"
  }
}
